services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: atlas-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "Your_password123" -Q "SELECT 1" -C || exit 1
      interval: 10s
      timeout: 5s
      retries: 20

  api:
    build:
      context: .
      dockerfile: src/Atlas.Api/Dockerfile
    container_name: atlas-api
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Server=db,1433;Database=AtlasTaskHub;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
      - Jwt__Issuer=AtlasTaskHub
      - Jwt__Audience=AtlasTaskHub
      - Jwt__SigningKey=dev_signing_key_change_me_please_32chars
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
